# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realmSwiftSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'RealmSwift'
  use_frameworks!

  # Pods for realmSwiftSample

  target 'realmSwiftSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realmSwiftSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
