# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  # Pods for ChatSample

  target 'ChatSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatSampleUITests' do
    # Pods for testing
  end

end
