# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseSamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  use_frameworks!

  # Pods for FirebaseSamples

  target 'FirebaseSamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseSamplesUITests' do
    # Pods for testing
  end

end
