# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GrowthPushSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Growthbeat'
  use_frameworks!

  # Pods for GrowthPushSample

  target 'GrowthPushSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrowthPushSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
