# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseDynamicLinksSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 pod 'Firebase/Core'
 pod 'Firebase/DynamicLinks'
 use_frameworks!

  # Pods for FirebaseDynamicLinksSample

  target 'FirebaseDynamicLinksSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseDynamicLinksSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
