# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EZAudioSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'EZAudio', '~>1.0'

  # Pods for EZAudioSample

  target 'EZAudioSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EZAudioSampleUITests' do
    # Pods for testing
  end

end
